#!/usr/bin/env python
#
# Copyright (c) 2011 Joshua Tacoma
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import cgi
import datetime
import json
import math
import os
import sys

import cgitb
cgitb.enable()

import swisseph as swe

def getinfo(jd):

    flag = swe.FLG_HELCTR | swe.FLG_SWIEPH | swe.FLG_SPEED
    
    keys = ['lon', 'lat', 'dist', 'lons', 'lats', 'dists']
    bodies = []
    for body in range(23):
        values = swe.calc_ut(jd, body, flag)
        info = dict(zip(keys, values))
        info['body_id'] = body
        bodies.append(info)

    swe.close()
    
    return {
            'jd' : jd,
            'bodies'  : bodies,
        }

def main():
    form = cgi.FieldStorage()
    date_raw = form.getfirst('d', datetime.datetime.now().isoformat().split('T')[0])
    date = datetime.datetime.strptime(date_raw, '%Y-%m-%d')
    jd = swe.julday(date.year, date.month, date.day, date.hour)
    span = int(form.getfirst('s', 1))
    result = []
    for i in range(span):
        result.append(getinfo(jd + i))
    print 'Content-type: application/json'
    print
    print json.dumps(result)

if __name__ == '__main__':
    main()
